// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace NetCore.Coupon.Contracts.Response
{


    public class ItemInfoModel
    {

        [JsonProperty("itemId")]
        public string ItemId { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("picsPath")]
        public string[] PicsPath { get; set; }

        [JsonProperty("favcount")]
        public string Favcount { get; set; }

        [JsonProperty("stuffStatus")]
        public string StuffStatus { get; set; }

        [JsonProperty("itemUrl")]
        public string ItemUrl { get; set; }

        [JsonProperty("sku")]
        public bool Sku { get; set; }

        [JsonProperty("location")]
        public string Location { get; set; }

        [JsonProperty("saleLine")]
        public string SaleLine { get; set; }

        [JsonProperty("categoryId")]
        public string CategoryId { get; set; }

        [JsonProperty("itemTypeName")]
        public string ItemTypeName { get; set; }

        [JsonProperty("itemTypeLogo")]
        public string ItemTypeLogo { get; set; }

        [JsonProperty("itemIcon")]
        public string ItemIcon { get; set; }

        [JsonProperty("isMakeup")]
        public bool IsMakeup { get; set; }
    }

    public class EvaluateInfo
    {

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("score")]
        public string Score { get; set; }

        [JsonProperty("highGap")]
        public string HighGap { get; set; }
    }

    public class ActionUnit
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }

        [JsonProperty("url")]
        public string Url { get; set; }

        [JsonProperty("track")]
        public string Track { get; set; }
    }

    public class Seller
    {

        [JsonProperty("userNumId")]
        public string UserNumId { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("nick")]
        public string Nick { get; set; }

        [JsonProperty("creditLevel")]
        public string CreditLevel { get; set; }

        [JsonProperty("goodRatePercentage")]
        public string GoodRatePercentage { get; set; }

        [JsonProperty("shopTitle")]
        public string ShopTitle { get; set; }

        [JsonProperty("shopId")]
        public string ShopId { get; set; }

        [JsonProperty("weitaoId")]
        public string WeitaoId { get; set; }

        [JsonProperty("fansCount")]
        public string FansCount { get; set; }

        [JsonProperty("fansCountText")]
        public string FansCountText { get; set; }

        [JsonProperty("evaluateInfo")]
        public EvaluateInfo[] EvaluateInfo { get; set; }

        [JsonProperty("picUrl")]
        public string PicUrl { get; set; }

        [JsonProperty("starts")]
        public string Starts { get; set; }

        [JsonProperty("shopPromtionType")]
        public string ShopPromtionType { get; set; }

        [JsonProperty("actionUnits")]
        public ActionUnit[] ActionUnits { get; set; }
    }

    public class Prop
    {

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("value")]
        public string Value { get; set; }
    }

    public class DescInfo
    {

        [JsonProperty("briefDescUrl")]
        public string BriefDescUrl { get; set; }

        [JsonProperty("fullDescUrl")]
        public string FullDescUrl { get; set; }

        [JsonProperty("showFullDetailDesc")]
        public string ShowFullDetailDesc { get; set; }

        [JsonProperty("pcDescUrl")]
        public string PcDescUrl { get; set; }

        [JsonProperty("h5DescUrl")]
        public string H5DescUrl { get; set; }

        [JsonProperty("h5DescUrl2")]
        public string H5DescUrl2 { get; set; }

        [JsonProperty("moduleDescUrl2")]
        public string ModuleDescUrl2 { get; set; }
    }

    public class Data
    {

        [JsonProperty("itemInfoModel")]
        public ItemInfoModel ItemInfoModel { get; set; }

        [JsonProperty("seller")]
        public Seller Seller { get; set; }

        [JsonProperty("props")]
        [JsonIgnore]
        public Prop[] Props { get; set; }

        [JsonProperty("descInfo")]
        [JsonIgnore]
        public DescInfo DescInfo { get; set; }
    }

    public class TaobaoProductDetailV5Response
    {

        [JsonProperty("api")]
        [JsonIgnore]
        public string Api { get; set; }

        [JsonProperty("v")]
        [JsonIgnore]
        public string V { get; set; }

        [JsonProperty("ret")]
        [JsonIgnore]
        public string[] Ret { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

}
