// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace NetCore.Coupon.Contracts.Entity
{

    public class TaokeJidiItem
    {

        [JsonProperty("id")]
        public string Id { get; set; }

        [JsonProperty("goods_name")]
        public string GoodsName { get; set; }

        [JsonProperty("goods_id")]
        public string GoodsId { get; set; }

        [JsonProperty("cate_id")]
        public string CateId { get; set; }

        [JsonProperty("cate_name")]
        public string CateName { get; set; }

        [JsonProperty("goods_url")]
        public string GoodsUrl { get; set; }

        [JsonProperty("pic")]
        public string Pic { get; set; }

        [JsonProperty("price")]
        public string Price { get; set; }

        [JsonProperty("price_after_coupons")]
        public string PriceAfterCoupons { get; set; }

        [JsonProperty("price_coupons")]
        public string PriceCoupons { get; set; }

        [JsonProperty("sales")]
        public string Sales { get; set; }

        [JsonProperty("rate")]
        public string Rate { get; set; }

        [JsonProperty("commission_type")]
        public string CommissionType { get; set; }

        [JsonProperty("commission_type_name")]
        public string CommissionTypeName { get; set; }

        [JsonProperty("quan_link")]
        public string QuanLink { get; set; }

        [JsonProperty("seller_id")]
        public string SellerId { get; set; }

        [JsonProperty("quan_id")]
        public string QuanId { get; set; }

        [JsonProperty("quan_shengyu")]
        public string QuanShengyu { get; set; }

        [JsonProperty("quan_zhong")]
        public string QuanZhong { get; set; }

        [JsonProperty("quan_ling")]
        public string QuanLing { get; set; }

        [JsonProperty("quan_expired_time")]
        public string QuanExpiredTime { get; set; }

        [JsonProperty("quan_note")]
        public string QuanNote { get; set; }

        [JsonProperty("quan_guid_content")]
        public string QuanGuidContent { get; set; }

        [JsonProperty("quan_qq_img")]
        public string QuanQqImg { get; set; }

        [JsonProperty("src")]
        public string Src { get; set; }

        [JsonProperty("jhs")]
        public string Jhs { get; set; }

        [JsonProperty("tqg")]
        public string Tqg { get; set; }

        [JsonProperty("gold")]
        public string Gold { get; set; }

        [JsonProperty("freight")]
        public string Freight { get; set; }

        [JsonProperty("abroad")]
        public string Abroad { get; set; }

        [JsonProperty("flagship")]
        public string Flagship { get; set; }
    }

    public class TaokeJidiDataResponse
    {

        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("msg")]
        public string Msg { get; set; }

        [JsonProperty("data")]
        public TaokeJidiItem[] Data { get; set; }

        [JsonProperty("dialog")]
        public string Dialog { get; set; }
    }

}
