// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace NetCore.Coupon.Contracts.Entity
{

    public class TaokeZhushouItem
    {
        /// <summary>
        /// 商品ID 
        /// </summary>
        [JsonProperty("goods_id")]
        public string GoodsId { get; set; }
        /// <summary>
        /// 商品主图
        /// </summary>
        [JsonProperty("goods_pic")]
        public string GoodsPic { get; set; }
        /// <summary>
        /// 商品推广长图 
        /// </summary>
        [JsonProperty("goods_long_pic")]
        public string GoodsLongPic { get; set; }
        /// <summary>
        /// 商品标题
        /// </summary>
        [JsonProperty("goods_title")]
        public string GoodsTitle { get; set; }
        /// <summary>
        /// 商品短标题 
        /// </summary>
        [JsonProperty("goods_short_title")]
        public string GoodsShortTitle { get; set; }
        /// <summary>
        /// 商品文案
        /// </summary>
        [JsonProperty("goods_intro")]
        public string GoodsIntro { get; set; }
        /// <summary>
        /// //商品分类 int 1女装 2男装 3内衣 4数码家电 5美食 6美妆个护 7母婴 8鞋包配饰 9家居家装 10文体车品 11其他
        /// </summary>
        [JsonProperty("goods_cate_id")]
        public int GoodsCateId { get; set; }
        /// <summary>
        /// 商品原价 
        /// </summary>
        [JsonProperty("goods_price")]
        public string GoodsPrice { get; set; }
        /// <summary>
        /// 商品销量
        /// </summary>
        [JsonProperty("goods_sale_num")]
        public int GoodsSaleNum { get; set; }
        /// <summary>
        /// 佣金
        /// </summary>
        [JsonProperty("commission_rate")]
        public double CommissionRate { get; set; }
        /// <summary>
        /// 卖家ID
        /// </summary>
        [JsonProperty("seller_id")]
        public string SellerId { get; set; }
        /// <summary>
        /// 券ID
        /// </summary>
        [JsonProperty("coupon_id")]
        public string CouponId { get; set; }
        /// <summary>
        /// 优惠券满
        /// </summary>
        [JsonProperty("coupon_apply_amount")]
        public string CouponApplyAmount { get; set; }
        /// <summary>
        /// 优惠券减
        /// </summary>
        [JsonProperty("coupon_amount")]
        public string CouponAmount { get; set; }
        /// <summary>
        /// 券开始时间
        /// </summary>
        [JsonProperty("coupon_start_time")]
        public string CouponStartTime { get; set; }
        /// <summary>
        /// 券结束时间
        /// </summary>
        [JsonProperty("coupon_end_time")]
        public string CouponEndTime { get; set; }
        /// <summary>
        /// //是否是天猫int 1是 其他否
        /// </summary>
        [JsonProperty("is_tmall")]
        public int IsTmall { get; set; }
        /// <summary>
        ///  //是否取聚划算 int  0 否  1 是
        /// </summary>
        [JsonProperty("juhuasuan")]
        public int Juhuasuan { get; set; }
        /// <summary>
        ///  是否取淘抢购 int  0 否  1 是
        /// </summary>
        [JsonProperty("taoqianggou")]
        public int Taoqianggou { get; set; }
        /// <summary>
        /// 是否运费险 int  0 否  1 是
        /// </summary>
        [JsonProperty("yunfeixian")]
        public int Yunfeixian { get; set; }
        /// <summary>
        /// 是否金牌卖家 int  0 否  1 是
        /// </summary>
        [JsonProperty("jinpai")]
        public int Jinpai { get; set; }
        /// <summary>
        /// 是否极有家商品 int  0 否  1 是
        /// </summary>
        [JsonProperty("jiyoujia")]
        public int Jiyoujia { get; set; }
        /// <summary>
        /// 是否海淘商品 int  0 否  1 是
        /// </summary>
        [JsonProperty("haitao")]
        public int Haitao { get; set; }
        /// <summary>
        /// DSR描述评分 float
        /// </summary>
        [JsonProperty("dsr")]
        public double Dsr { get; set; }
    }

    public class TaokeZhushouDataResponse
    {

        [JsonProperty("code")]
        public int Code { get; set; }

        [JsonProperty("msg")]
        public string Msg { get; set; }

        [JsonProperty("api_version")]
        public string ApiVersion { get; set; }

        [JsonProperty("api_name")]
        public string ApiName { get; set; }

        [JsonProperty("total")]
        public int Total { get; set; }

        [JsonProperty("data")]
        public List<TaokeZhushouItem> Data { get; set; }
    }

}
